### ISSUE TITLE
New save file corrupted after trying to convert from UWP to Steam.

### ISSUE THREAD

**Issue by jordanyoong1** [BelovedTomboyishGirl/Nier-Automata-Save-Converter#1]
Title.

**Comment by Roadou** [comment]
Can you share me your steam save and your Xbox save ?

**Comment by jordanyoong1** [comment]
[BA3843D21A154F5EB6F70EE7E83A962C.zip](https://github.com/BelovedTomboyishGirl/Nier-Automata-Save-Converter/files/6249856/BA3843D21A154F5EB6F70EE7E83A962C.zip)

Unfortunately I already manually replaced my steam's save file using hex editor, but I tried two different steam save file and both corrupted in the end so I guess it doesn't matter?

**Comment by Roadou** [comment]
Since people i have asked don't have problem with this tool, it's likely you have do a mistake or misunderstanding how it works, i close this issue.

**Comment by Roadou** [comment]
Fixed in #5 
Problem was software related, my excuses
