### ISSUE TITLE
Resource file "Properties\Resources.resx" cannot be found

### ISSUE THREAD

**Issue by crsnplusplus** [BelovedTomboyishGirl/Nier-Automata-Save-Converter#2]
Hi I just tried to build this project, but it complains about Resources.resx being missing.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Resource file "Properties\Resources.resx" cannot be found.	NieR Automata Save Converter			

```

![image](https://user-images.githubusercontent.com/400740/114314340-7cba0780-9afa-11eb-8ecc-0e10c67c46ed.png)

Am I missing some generation step?

**Comment by Roadou** [comment]
Fixed in #5
