### ISSUE TITLE
Mistake in confirmation dialog

### ISSUE THREAD

**Issue by Miminepho** [BelovedTomboyishGirl/Nier-Automata-Save-Converter#3]
![image](https://user-images.githubusercontent.com/30994617/114396942-71b8b300-9b9e-11eb-86c7-d24709450a8b.png)

When converting from Steam to Microsoft Store, the confirmation dialog says "(Your Microsoft SaveGame)" when referring to the Steam save file. 

_Otherwise, thank you for this tool, it works great :)_

**Comment by Roadou** [comment]
Fixed in #5
