### ISSUE TITLE
Program says completed but i can't open the save.

### ISSUE THREAD

**Issue by HeroHuntr** [BelovedTomboyishGirl/Nier-Automata-Save-Converter#4]
As the title states I ran the program and it said had completed. But when I started up the game and tried to load the save file it didn't work. The game just simply wouldn't do anything when I tried to play on that save. I don't know if I did something wrong or what.

Edit: I am trying to convert from Microsoft Store/ Xbox App ver to steam. Could my problem stem from having items that are considered DLC by steam but come with the Microsoft ver?

**Comment by menio** [comment]
I had the same issue as you. 

Going from Xbox App to Steam. This app isn't converting the saves properly. I instead ended up doing the manual steps described in this wiki https://www.pcgamingwiki.com/wiki/NieR:_Automata#Transfer_saves_between_versions and it worked for me. You will need to use a Hex Editor like HxD.

**Comment by Roadou** [comment]
Fixed in #5
